[package]
name = "btagsil"
description = "BTAGSIL = a Bullshit Text Adventure Game where Sky Is the Limit"
author = "Einax"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
